[package]
name = "flux-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flux-attrs-proc-macros = { path = "../flux/flux-attrs-proc-macros" }

[profile.dev]
incremental = false